baseURL = 'https://www.gunayorbay.com/'
languageCode = 'en-us'
title = 'Günay Orbay, PHD'
theme = 'cactus'

[params]
  github = 'https://github.com/gunayorbay'
  mastodon = 'https://mastodon.social/@gorbay'
  instagram = 'https://www.instagram.com/gunayorbay/'
  excerpts = 'true'
  mainSections = [ 'posts' ]
  description = "Welcome to my website where I share about my research, work, and interests."

[[params.social]]
  name = "github"
  link = "https://github.com/gunayorbay"

[[params.social]]
  name = "mastodon"
  link = "https://mastodon.social/@gorbay"

[[params.social]]
  name = "instagram"
  link = "https://www.instagram.com/gunayorbay/"

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'about me'
  url = '/about/'
[[menu.main]]
  identifier = 'posts'
  name = 'blog posts'
  url = '/posts/'
[[menu.main]]
  identifier = 'publications'
  name = 'my publications'
  url = '/publications/'
